version: '3.3'

services:
  mav_active_planner:
    network_mode: host
    environment:
    - DISPLAY=$DISPLAY
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=graphics
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/tmp/.docker.xauth
    - SSH_AUTH_SOCK=/ssh-agent
    - ROS_IP=$ROS_IP
    - ROS_MASTER_URI=$ROS_MASTER_URI
    volumes:
    - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
    # - '../:/ws'
    - ${SSH_AUTH_SOCK}:/ssh-agent
    - '/tmp/.docker.xauth:/tmp/.docker.xauth'
    devices:
    - /dev/dri
    privileged: true
    image: ghcr.io/cvg/mav_active_3d_planning:master
    command:  bash -c "source ../devel/setup.bash && roslaunch active_3d_planning_app_reconstruction sutd_experiment.launch"

